// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoCadAlunoAPI.DATA.Context;

namespace ProjetoCadAlunoAPI.Migrations
{
    [DbContext(typeof(ProjetoCadAlunoContext))]
    [Migration("20211126210634_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.12");

            modelBuilder.Entity("ProjetoCadAluno.DOMAIN.Models.Aluno", b =>
                {
                    b.Property<string>("Matricula")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<int>("Situacao")
                        .HasColumnType("int");

                    b.Property<string>("Telefone")
                        .HasColumnType("longtext");

                    b.HasKey("Matricula");

                    b.ToTable("Aluno");
                });
#pragma warning restore 612, 618
        }
    }
}
